<ips:template parameters="$chart, $type, $options, $format=NULL" />
<table class="ipsTable" data-ipsChart data-ipsChart-type="{$type}" data-ipsChart-extraOptions='{$options|raw}' {{if $format}}data-ipsChart-format='{$format}'{{endif}}>
	<thead>
		<tr>
			{{foreach $chart->headers as $data}}
				<th data-colType="{$data['type']}">{$data['label']}</th>
			{{endforeach}}
		</tr>
	</thead>
	<tbody>
		{{foreach $chart->rows as $row}}
			<tr>
				{{foreach $row as $value}}
					<td>{$value}</td>
				{{endforeach}}
			</tr>
		{{endforeach}}
	</tbody>
</table>
<div></div>