<ips:template parameters="$name, $value, $pollData, $allowPollOnly" />
<div data-controller='core.front.core.pollEditor' data-pollName='{$name}' data-showCounts='{{if member.modPermission('can_edit_poll_votes')}}true{{else}}false{{endif}}' data-maxQuestions="{expression="\IPS\Settings::i()->max_poll_questions"}" data-maxChoices="{expression="\IPS\Settings::i()->max_poll_choices"}" class='cPoll'>	
	<noscript>
		{{if $value}}
		<input type="hidden" name="{$name}[fallback]" value="{$value->pid}">
		{{endif}}
		{lang="poll_no_js"}
	</noscript>
	<div class='ipsForm_vertical ipsForm_noLabels ipsJS_show'>
		<ul class='ipsList_reset ipsAreaBackground_light ipsBox ipsBox_transparent ipsPad'>
			<li class='ipsFieldRow'>
				<input type='text' class='ipsField_primary ipsField_fullWidth' placeholder='{lang="poll_title"}' name="{$name}[title]" maxlength="255" {{if $value}}value="{$value->poll_question}"{{endif}}>
			</li>
			{{if settings.poll_allow_public or (settings.ipb_poll_only and $allowPollOnly)}}
				<li class='ipsFieldRow'>
					<ul class='ipsFieldRow_content ipsList_reset'>
						{{if settings.poll_allow_public}}
							<li class='ipsFieldRow_inlineCheckbox'>
								<span class='ipsCustomInput'>
									<input type="checkbox" name="{$name}[public]" id='elPoll_{$name}_public' {{if $value and $value->poll_view_voters}}checked{{endif}}>
									<span></span>
								</span>
								<label for='elPoll_{$name}_public'>{lang="make_votes_public"}</label>
							</li>
						{{endif}}
						{{if settings.ipb_poll_only and $allowPollOnly}}
							<li class='ipsFieldRow_inlineCheckbox'>
								<span class='ipsCustomInput'>
									<input type="checkbox" name="{$name}[poll_only]" id='elPoll_{$name}_pollOnly' {{if $value and $value->poll_only}}checked{{endif}}>
									<span></span>
								</span>
								<label for='elPoll_{$name}_pollOnly'>{lang="poll_only_content"}</label>
							</li>
						{{endif}}
					</ul>
				</li>
			{{endif}}
		</ul>
	</div>
	<br> 

	<section data-role='pollContainer'>

	</section>

	<a href='#' data-action='addQuestion' class='ipsButton ipsButton_medium ipsButton_alternate ipsJS_show' title='{lang="add_poll_question_title"}'><i class='fa fa-plus-circle'></i> {lang="add_poll_question"}</a>
</div>