<ips:template parameters="$table, $headers, $rows" />
{{if count( $rows )}}
	{{foreach $rows as $row}}
		<li class='ipsDataItem'>		
			{{if \IPS\Settings::i()->reputation_point_types != 'like'}}
				<div class='ipsDataItem_generic ipsDataItem_size1'>
					{{if $row->rep_rating === 1}}
						<span class='ipsButton ipsButton_large ipsButton_narrow ipsButton_rep ipsButton_repUp ipsButton_noHover cProfileRepLog_button'>
							<i class='fa fa-arrow-up'></i>
						</span>
					{{else}}
						<span class='ipsButton ipsButton_large ipsButton_narrow ipsButton_rep ipsButton_repDown ipsButton_noHover cProfileRepLog_button'>
							<i class='fa fa-arrow-down'></i>
						</span>
					{{endif}}
				</div>
			{{endif}}
			<div class='ipsDataItem_generic ipsDataItem_size2 ipsType_center ipsResponsive_hidePhone'>
				{{if $row->rep_member == \IPS\Request::i()->id}}
					{template="userPhoto" group="global" app="core" params="\IPS\Member::load( \IPS\Request::i()->id ), 'mini'"}
				{{else}}
					{template="userPhoto" group="global" app="core" params="\IPS\Member::load( $row->rep_member ), 'mini'"}
				{{endif}}
			</div>
			<div class='ipsDataItem_main'>
				<span class=''>
					{{if \IPS\Settings::i()->reputation_point_types != 'like'}}
						{{if $row instanceof \IPS\Content\Comment or $row instanceof \IPS\Content\Review}}
							{{$item = $row->item();}}
							{{if $row->rep_member != \IPS\Request::i()->id}}
								{lang="replog_rate_comment_received" htmlsprintf="\IPS\Member::load( $row->rep_member_received )->link(), \IPS\Member::load( $row->rep_member )->link()"} <a href='{$item->url()}'>{$item->mapped('title')}</a>
							{{else}}
								{{if $row->rep_member_received}}
									{lang="replog_rate_comment_gave" htmlsprintf="\IPS\Member::load( $row->rep_member )->link(), \IPS\Member::load( $row->rep_member_received )->link()"} <a href='{$item->url()}'>{$item->mapped('title')}</a>
								{{else}}
									{lang="replog_rate_comment_gave_no_recipient" htmlsprintf="\IPS\Member::load( $row->rep_member )->link()"} <a href='{$item->url()}'>{$item->mapped('title')}</a>
								{{endif}}
							{{endif}}
						{{else}}
							{{if $row->rep_member != \IPS\Request::i()->id}}
								{lang="replog_rate_item_received" htmlsprintf="\IPS\Member::load( $row->rep_member_received )->link(), \IPS\Member::load( $row->rep_member )->link(), $row->indefiniteArticle()"} <a href='{$row->url()}'>{$row->mapped('title')}</a>
							{{else}}
								{{if $row->rep_member_received}}
									{lang="replog_rate_item_gave" htmlsprintf="\IPS\Member::load( $row->rep_member )->link(), \IPS\Member::load( $row->rep_member_received )->link(), $row->indefiniteArticle()"} <a href='{$row->url()}'>{$row->mapped('title')}</a>
								{{else}}
									{lang="replog_rate_item_gave_no_recipient" htmlsprintf="\IPS\Member::load( $row->rep_member )->link(), $row->indefiniteArticle()"} <a href='{$row->url()}'>{$row->mapped('title')}</a>
								{{endif}}
							{{endif}}
						{{endif}}
					{{else}}
						<strong>
							{{if $row instanceof \IPS\Content\Comment or $row instanceof \IPS\Content\Review}}
								{{$item = $row->item();}}
								{{if $row->rep_member_received}}
									{lang="replog_like_comment" htmlsprintf="\IPS\Member::load( $row->rep_member )->link(), $row->url(), $row->indefiniteArticle(), \IPS\Member::load( $row->rep_member_received )->link()"} <a href='{$item->url()}'>{$item->mapped('title')}</a>
								{{else}}
									{lang="replog_like_comment_no_recipient" htmlsprintf="\IPS\Member::load( $row->rep_member )->link(), $row->url(), $row->indefiniteArticle()"} <a href='{$item->url()}'>{$item->mapped('title')}</a>
								{{endif}}
							{{else}}
								{{if $row->rep_member_received}}
									{lang="replog_like_item" htmlsprintf="\IPS\Member::load( $row->rep_member )->link(), $row->indefiniteArticle(), \IPS\Member::load( $row->rep_member_received )->link()"} <a href='{$row->url()}'>{$row->mapped('title')}</a>
								{{else}}
									{lang="replog_like_item_no_recipient" htmlsprintf="\IPS\Member::load( $row->rep_member )->link(), $row->indefiniteArticle()"} <a href='{$row->url()}'>{$row->mapped('title')}</a>
								{{endif}}
							{{endif}}
						</strong>
					{{endif}}
				</span>
				<span class='ipsType_light ipsType_medium'>&nbsp;&nbsp;{datetime="$row->rep_date"}</span>
				<br>
				{{if $row->truncated()}}
					<div class='ipsType_medium ipsType_richText ipsContained cProfileRepLog_text' data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='2 lines'>
						{$row->truncated()|raw}
					</div>
				{{endif}}
			</div>
		</li>
	{{endforeach}}
{{endif}}
