<ips:template parameters="$status, $authorData=NULL, $profileOwnerData=NULL, $condensed=FALSE" />

<li {{if !$condensed}}data-controller='core.front.statuses.status'{{endif}} class='ipsStreamItem ipsStreamItem_contentBlock {{if $condensed}}ipsStreamItem_condensed{{endif}} {{if $status->hidden()}} ipsModerated{{endif}} ipsAreaBackground_reset ipsPad' data-timestamp='{$status->date}' data-role='activityItem' data-statusid="{$status->id}">
	<a id='status-{$status->id}'></a>
	<div class='ipsStreamItem_container'>
		<div class='ipsStreamItem_header ipsPhotoPanel ipsPhotoPanel_mini'>
			<span class='ipsStreamItem_contentType' data-ipsTooltip title='{lang="status_update"}'><i class='fa fa-user'></i></span>
			{{if $authorData}}
				{template="userPhotoFromData" group="global" app="core" params="$authorData['member_id'], $authorData['name'], $authorData['members_seo_name'], \IPS\Member::photoUrl( $authorData ), ( $condensed ? 'tiny' : 'mini' )"}
			{{else}}
				{template="userPhoto" group="global" app="core" params="$status->author(), ( $condensed ? 'tiny' : 'mini' )"}
			{{endif}}
			<div>
				<h2 class='ipsType_reset ipsStreamItem_title {{if $condensed}}ipsStreamItem_titleSmall{{endif}} ipsType_break'>
					{{if $status->member_id != $status->author()->member_id}}
						<ul class='ipsList_inline ipsList_noSpacing'>
							<li>
								<strong>
									{{if $authorData}}
										{template="userLinkFromData" group="global" app="core" params="$authorData['member_id'], $authorData['name'], $authorData['members_seo_name']"}
									{{else}}
										{template="userLink" app="core" group="global" location="front" params="$status->author()"}
									{{endif}}
								</strong>
							</li>
							<li>
								&nbsp;<i class='fa fa-angle-right'></i>&nbsp;
							</li>
							<li>
								<strong>
									{{if $profileOwnerData}}
										{template="userLinkFromData" group="global" app="core" params="$profileOwnerData['member_id'], $profileOwnerData['name'], $profileOwnerData['members_seo_name']"}
									{{else}}
										{member="link()" id="$status->member_id" raw="true"}
									{{endif}}
								</strong>
							</li>
						</ul>
					{{else}}
						<strong>
							{{if $authorData}}
								{template="userLinkFromData" group="global" app="core" params="$authorData['member_id'], $authorData['name'], $authorData['members_seo_name']"}
							{{else}}
								{template="userLink" app="core" group="global" location="front" params="$status->author()"}
							{{endif}}
						</strong>
					{{endif}}
					{{if $status->hidden()}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_warning" data-ipsTooltip title='{lang="hidden"}'><i class='fa fa-eye-slash'></i></span>
					{{endif}}
				</h2>
				{{if $condensed}}
					<ul class='ipsList_inline ipsStreamItem_stats ipsType_light'>
						<li>
							<a href='{$status->url()}' class='ipsType_blendLinks'><i class='fa fa-clock-o'></i> {datetime="$status->date"}</a>
						</li>
					</ul>
					<p class="ipsStreamItem_status ipsType_reset">
						{{if $status->member_id == $status->author()->member_id}}
							{{if $authorData}}
								{lang="member_posted_status_self" htmlsprintf="$authorData['name']"}
							{{else}}
								{lang="member_posted_status_self" htmlsprintf="$status->author()->name"}
							{{endif}}
						{{else}}
							{{if $authorData}}
								{lang="member_posted_status_other" htmlsprintf="$authorData['name'], $profileOwnerData['name']"}
							{{else}}
								{lang="member_posted_status_other" htmlsprintf="$status->author()->name, \IPS\Member::load( $status->member_id )->name"}
							{{endif}}
						{{endif}}
					</p>
				{{endif}}
			</div>
		</div>
		{{if !$condensed}}
			<div class='ipsStreamItem_snippet'>
				<div class='ipsType_richText ipsType_normal ipsContained'>{$status->content|raw}</div>
			</div>
		{{endif}}
		{{if !$condensed}}
			<ul class='ipsList_inline ipsStreamItem_meta ipsFaded_withHover'>
				<li class='ipsType_medium'>{{if $status->locked()}}<i class='fa fa-lock'></i>{{endif}} <a href='{$status->url()}' class='ipsType_blendLinks'><span class='ipsType_light'><i class='fa fa-clock-o'></i> {datetime="$status->date"}</span></a></li>
				{{if $status instanceof \IPS\Content\Reputation and settings.reputation_enabled and ( $status->reputation() or ( $status->canGiveReputation( 1 ) or $status->canGiveReputation( -1 ) ) )}}
					<li class='ipsType_light ipsType_medium'>{template="reputationMini" group="global" app="core" params="$status->reputation(), $status->canGiveReputation( 1 ), $status->canGiveReputation( -1 ), $status->url('showRep'), $status->url('rep')"}</li>
				{{endif}}
				{{if $status->canDelete() || $status->canLock() || $status->canUnlock() || $status->canHide() || $status->canUnhide()}}
					<li>
						<a href='#elStatus_{$status->id}_menu' data-ipsMenu data-ipsMenu-activeClass='ipsFaded_cancel' id='elStatus_{$status->id}' class='ipsFaded ipsFaded_more'>{lang="options"} <i class='fa fa-caret-down'></i></a>
						<ul class='ipsMenu ipsMenu_narrow ipsHide' id='elStatus_{$status->id}_menu'>
							{{if !$status->locked() and $status->canLock()}}
								<li class='ipsMenu_item'><a href="{$status->url('moderate')->setQueryString( 'action', 'lock' )->csrf()}">{lang="lock"}</a></li>
							{{elseif $status->locked() and $status->canUnlock()}}
								<li class='ipsMenu_item'><a href="{$status->url('moderate')->setQueryString( 'action', 'unlock' )->csrf()}">{lang="unlock"}</a></li>
							{{endif}}
							{{if !$status->hidden() and $status->canHide()}}
								<li class='ipsMenu_item'><a href='{$status->url('moderate')->setQueryString( 'action', 'hide' )->csrf()}'>{lang="hide"}</a></li>
							{{elseif $status->hidden() and $status->canUnhide()}}
								<li class='ipsMenu_item'><a href='{$status->url('moderate')->setQueryString( 'action', 'unhide' )->csrf()}'>{lang="unhide"}</a></li>
							{{endif}}
							{{if $status->canDelete()}}
								<li class='ipsMenu_item'><a data-confirm href="{$status->url('moderate')->setQueryString( 'action', 'delete' )->csrf()}">{lang="delete"}</a></li>
							{{endif}}
						</ul>
					</li>
				{{endif}}
				{{if !\IPS\Member::loggedIn()->group['gbw_no_report'] and !$status->hidden()}}
					<li><a href='{$status->url('report')}' data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-title="{lang="report"}" data-action='reportStatus' title='{lang="report_content"}' class='ipsFaded ipsFaded_more'>{lang="status_report"}</a></li>
				{{endif}}	
			</ul>
		{{endif}}
		{{if !$condensed && ( count( $status->comments() ) ||  $status->canComment() )}}
			<div class='ipsComment_feed ipsComment_subComments ipsType_medium'>
				<ol class="ipsList_reset" data-role='statusComments' data-currentPage='{expression="\IPS\Request::i()->page ? intval( \IPS\Request::i()->page ) : 1"}'>
					{template="statusReplies" group="statuses" params="$status"}
				</ol>
				{{if \IPS\core\Statuses\Status::canCreateReply( \IPS\Member::loggedIn() )}}
					<div class="ipsComment ipsFieldRow_fullWidth ipsAreaBackground_light ipsPad" data-role="replyComment">
						<div class="ipsComment_content ipsContained">
							{$status->commentForm()|raw}
						</div>
					</div>
				{{endif}}
			</div>
		{{endif}}	
	</div>
</li>