<ips:template parameters="$members, $filters, $activeFilter, $url, $contentLabel='members_member_posts', $contentCount='member_posts'" />
<div class='ipsBox' data-baseurl='{url="app=core&module=discover&controller=popular&tab=members" seoTemplate="leaderboard_members"}' data-resort='topMembers' data-tableID='topMembers' data-controller='core.global.core.table'>
	<div class='ipsAreaBackground_light'>
		<div class="ipsPad_half ipsClearfix ipsClear">
			<ul class="ipsButtonRow ipsPos_right ipsClearfix">
				<li>
					<a href="#elFilterByMenu_menu" id="elFilterByMenu" data-role='tableFilterMenu' data-ipsMenu data-ipsMenu-activeClass="ipsButtonRow_active" data-ipsMenu-selectable="radio"><span data-role="extraHtml">{$filters[ $activeFilter ][1]}</span> <i class="fa fa-caret-down"></i></a>
					<ul class='ipsMenu ipsMenu_auto ipsMenu_withStem ipsMenu_selectable ipsHide' data-role="tableFilterMenu" id='elFilterByMenu_menu'>
						{{foreach $filters as $key => $data}}
							<li data-action="tableFilter" data-ipsMenuValue='{$key}' class='ipsMenu_item {{if $key === $activeFilter}}ipsMenu_itemChecked{{endif}}'>
								<a href='{$url->setQueryString( array( 'filter' => $key ) )}'>{$data[1]}</a>
							</li>
						{{endforeach}}
					</ul>
				</li>
			</ul>
		</div>
		<section data-role="tableRows">
			{template="membersWrapper" group="popular" app="core" params="$members, $contentLabel, $contentCount"}
		</section>
	</div>
	<div class="ipsHide" data-role="tablePagination"></div>
</div>
