<ips:template parameters="" />
{{if settings.af_stafftoggle == 1}}
	<div class='ipsColumn ipsColumn_wide staffCol'>
		<div class="staffBlo">
			<ul class='ipsList_reset'>
				{{if settings.af_staff_header}}<h3>{setting="af_staff_header"}</h3>{{endif}}
				{{foreach explode("\n", settings.af_staff_members) as $members}}		
					{{$member = \IPS\Member::load( $members );}}
					<li class='{{if settings.af_staffshowimg == 1}}ipsPhotoPanel{{endif}}'>
						<div class='staffMembers'>
							{{if settings.af_staffshowimg == 1}} 
								<div class="stphoto">{template="userPhoto" group="global" app="core" params="$member, 'tiny'"}</div>
							{{endif}}
							{{if settings.af_staffshowname == '1' or settings.af_staffshowgroup == '1'}}
								<div class='staffName'>
									{{if settings.af_staffshowname == 1}}{template="userLinkFromData" group="global" app="core" params="$member->member_id, $member->name, $member->members_seo_name, $member->member_group_id"}{{endif}}
									{{if settings.af_staffshowgroup == 1}}<span class="groupName">{$member->groupName|raw}</span>{{endif}}
								</div>
							{{endif}}
						</div>
					</li> 
				{{endforeach}}
			</ul>
			{{if settings.af_staffdesc}}
				<section class='ipsType_normal ipsType_richText ipsType_break'>
					{setting="af_staffdesc"}
				</section>
			{{endif}}
		</div>
	</div>
{{endif}} 