<ips:template parameters="$item, $review" />
{{$idField = $review::$databaseColumnId;}}
{{if $review->isIgnored()}}
	<div class='ipsComment ipsComment_ignored ipsPad_half ipsType_light'>
		{lang="ignoring_content" sprintf="$review->author()->name"}
	</div>
{{else}}
	<a id='review-{$review->$idField}'></a>
	<article itemscope="" itemtype="http://schema.org/Comment" id="elReview_{$review->$idField}" class="ipsComment ipsComment_parent ipsClearfix ipsClear {{if $review->hidden()}}ipsModerated{{endif}}">
		{{if !$item->printedAverageReviewRating}}
			<div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
				<meta itemprop="ratingValue" content="{$item->averageReviewRating()}">
				<meta itemprop="reviewCount" content="{$item->reviewCount()}">
			</div>
			{{$item->printedAverageReviewRating = true;}}
		{{endif}}
		{template="review" group="global" app="core" params="$item, $review, $item::$formLangPrefix . 'review', $item::$application, $item::$module"}
	</article>
{{endif}}